pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'docker-demo'

steps:
- script: docker build -f DockerDemo/Dockerfile -t minhreg.azurecr.io/$(imageName) .
  workingDirectory: src/
  displayName: 'Docker Build'

- script: |
    docker login -u minhreg -p $pswd minhreg.azurecr.io
    docker push minhreg.azurecr.io/$(imageName)
  env:
    pswd: JYCWx9EQM59QtW0fa/tqKBeI0/lszWVN
  workingDirectory: src/
  displayName: 'Docker Push'
